// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kebzkwovkjipbpchugjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlYnprd292a2ppcGJwY2h1Z2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzY1NjUsImV4cCI6MjA1NzY1MjU2NX0.W0vOdw_wGoP0-HztmIkyz-kca3vc-4NdosGAcYAMPmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);